### ISSUE TITLE
the value in SQL

### ISSUE THREAD

**Issue by Gyyz** [BorealisAI/DT-Fixup#2]
Hi, thanks for the sharing code.

I am a little confused that the predicted results don't have a specified column value, is there any parameter that restricts the model?

For example, the generated SQL below:

SELECT students.cell_mobile_number FROM students WHERE students.first_name = **"value"** and students.last_name = **"value"**

What is the parameter if I want to get a specified column value rather than a terminal symbol?

Thanks.

**Comment by billy-inn** [comment]
This codebase doesn't support value prediction currently, as value is ignored in the Spider exact match evaluation.

**Comment by Gyyz** [comment]
Thanks for your reply.
