### ISSUE TITLE
Request the Docker env.

### ISSUE THREAD

**Issue by huybery** [BorealisAI/DT-Fixup#3]
Thank you for your great work! I would like to ask whether you have a docker environment that can run directly. At present, the project depends on a lot and is not easy to deploy directly. Thanks a lot!

**Comment by billy-inn** [comment]
Unfortunately, we don't have a readily available docker environment for now. However, we've tried to replicate our results successfully in this public docker image: conda/miniconda3-centos7. Hope it helps.
